### PR TITLE
Some functionality added

### PR DESCRIPTION
**Pull request by KristofferC**
Very nice package. I really needed something like this and I started writing my own but then I found yours  so it saved me a lot of time.

There was some stuff missing that I needed so I added them and created a PR in case you find them useful. Please comment if there is any parts you don't like.

In summary, this PR makes the following changes.
- Adds a differentiate function with the following syntax: `diff(p, :x, n=1)` This returns a new MultiPoly
  differentiated w.r.t `:x`, `n` times.
- Adds an integrate function that gives the primitive function of the polynomial with the syntax `integrate(p, :x, n=1)`.
- Changed from a normal dictionary to an ordered dictionary. 
  
  Before
  
  ``` julia
  julia> (x+y)^2
  MultiPoly.MPoly{Float64}(x^2 + 2.0x*y + y^2)
  
  julia> (x+y)^3
  MultiPoly.MPoly{Float64}(x^3 + y^3 + 3.0x^2*y + 3.0x*y^2)
  
  julia> (x+y)^4
  MultiPoly.MPoly{Float64}(y^4 + 4.0x^3*y + 6.0x^2*y^2 + 4.0x*y^3 + x^4)
  ```
  
  After:
  
  ``` julia
  julia> (x+y)^2
  MultiPoly.MPoly{Float64}(x^2 + 2.0x*y + y^2)
  
  julia> (x+y)^3
  MultiPoly.MPoly{Float64}(x^3 + 3.0x^2*y + 3.0x*y^2 + y^3)
  
  julia> (x+y)^4
  MultiPoly.MPoly{Float64}(x^4 + 4.0x^3*y + 6.0x^2*y^2 + 4.0x*y^3 + y^4)
  ```
- Makes evaluate return a number instead of a `MPoly`
- Add an `evaluate_basis` function (not sure about this name) has the same syntax as `evaluate` but instead returns a list of the contribution of all the terms in the polynomial.
- Add tests for everything

### CODE REVIEW

**Comment by daviddelaat** [comment]
Thanks! These look like very nice contributions! I also like the idea of using an ordered dictionary.

I agree with your comments that `diff(p, :x)` should return `zero(p)` if `:x` is not in `vars(p)`

I'll add you to the collaborators field in case you want to submit more changes.

**Comment by KristofferC** [comment]
Thank you for merging and adding me.

I was fixing the zero(p) thing for derivatives and I am not sure how to do with the integral.

If you have P(x,y) and try to integrate with respect to the symbol `:z`, should we add the symbol `:z` to vars, run `generate` on `z` and return z \* P(x,y)? The problem then is that the result is a P(x,y,z) but the user might not have run the generator for `z` yet.

**Comment by daviddelaat** [comment]
Yes, I think doing something like `return generator(MPoly{T}, symbol) * p` (for the n=1 case) is fine. There is no global state, so it's not a problem the user didn't run generate on z yet.

**Comment by daviddelaat** [comment]
I just added call methods, so it could look like `MPoly{T}(symbol) * p`

**Pull request merged**
